//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\Grammar\xpath.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GillSoft.ExpressionEvaluator {
using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public partial class xpathParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		AXIS=1, IDENT=2, PATHSEP=3, LBRAC=4, RBRAC=5, AT=6, EQ=7, COLON=8, COLONCOLON=9, 
		STRING=10, Whitespace=11;
	public const int
		RULE_path = 0, RULE_pathElement = 1, RULE_filter = 2, RULE_axis = 3, RULE_namespacePrefix = 4, 
		RULE_attribute = 5, RULE_element = 6;
	public static readonly string[] ruleNames = {
		"path", "pathElement", "filter", "axis", "namespacePrefix", "attribute", 
		"element"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "'/'", "'['", "']'", "'@'", null, "':'", "'::'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "AXIS", "IDENT", "PATHSEP", "LBRAC", "RBRAC", "AT", "EQ", "COLON", 
		"COLONCOLON", "STRING", "Whitespace"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "xpath.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	static xpathParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

	public xpathParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class PathContext : ParserRuleContext {
		public ITerminalNode[] PATHSEP() { return GetTokens(xpathParser.PATHSEP); }
		public ITerminalNode PATHSEP(int i) {
			return GetToken(xpathParser.PATHSEP, i);
		}
		public PathElementContext[] pathElement() {
			return GetRuleContexts<PathElementContext>();
		}
		public PathElementContext pathElement(int i) {
			return GetRuleContext<PathElementContext>(i);
		}
		public PathContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_path; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IxpathVisitor<TResult> typedVisitor = visitor as IxpathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPath(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PathContext path() {
		PathContext _localctx = new PathContext(Context, State);
		EnterRule(_localctx, 0, RULE_path);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 16;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 14; Match(PATHSEP);
				State = 15; pathElement();
				}
				}
				State = 18;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==PATHSEP );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PathElementContext : ParserRuleContext {
		public ElementContext element() {
			return GetRuleContext<ElementContext>(0);
		}
		public AxisContext axis() {
			return GetRuleContext<AxisContext>(0);
		}
		public FilterContext filter() {
			return GetRuleContext<FilterContext>(0);
		}
		public AttributeContext attribute() {
			return GetRuleContext<AttributeContext>(0);
		}
		public PathElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pathElement; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IxpathVisitor<TResult> typedVisitor = visitor as IxpathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPathElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PathElementContext pathElement() {
		PathElementContext _localctx = new PathElementContext(Context, State);
		EnterRule(_localctx, 2, RULE_pathElement);
		int _la;
		try {
			State = 28;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case AXIS:
			case IDENT:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 21;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AXIS) {
					{
					State = 20; axis();
					}
				}

				State = 23; element();
				State = 25;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LBRAC) {
					{
					State = 24; filter();
					}
				}

				}
				}
				break;
			case AT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 27; attribute();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FilterContext : ParserRuleContext {
		public AttributeContext attr;
		public ElementContext elem;
		public IToken value;
		public ITerminalNode LBRAC() { return GetToken(xpathParser.LBRAC, 0); }
		public ITerminalNode EQ() { return GetToken(xpathParser.EQ, 0); }
		public ITerminalNode RBRAC() { return GetToken(xpathParser.RBRAC, 0); }
		public ITerminalNode STRING() { return GetToken(xpathParser.STRING, 0); }
		public AttributeContext attribute() {
			return GetRuleContext<AttributeContext>(0);
		}
		public ElementContext element() {
			return GetRuleContext<ElementContext>(0);
		}
		public FilterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_filter; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IxpathVisitor<TResult> typedVisitor = visitor as IxpathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFilter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FilterContext filter() {
		FilterContext _localctx = new FilterContext(Context, State);
		EnterRule(_localctx, 4, RULE_filter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 30; Match(LBRAC);
			State = 33;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case AT:
				{
				State = 31; _localctx.attr = attribute();
				}
				break;
			case IDENT:
				{
				State = 32; _localctx.elem = element();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 35; Match(EQ);
			State = 36; _localctx.value = Match(STRING);
			State = 37; Match(RBRAC);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AxisContext : ParserRuleContext {
		public IToken name;
		public ITerminalNode COLONCOLON() { return GetToken(xpathParser.COLONCOLON, 0); }
		public ITerminalNode AXIS() { return GetToken(xpathParser.AXIS, 0); }
		public AxisContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_axis; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IxpathVisitor<TResult> typedVisitor = visitor as IxpathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAxis(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AxisContext axis() {
		AxisContext _localctx = new AxisContext(Context, State);
		EnterRule(_localctx, 6, RULE_axis);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 39; _localctx.name = Match(AXIS);
			State = 40; Match(COLONCOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespacePrefixContext : ParserRuleContext {
		public IToken name;
		public ITerminalNode IDENT() { return GetToken(xpathParser.IDENT, 0); }
		public NamespacePrefixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespacePrefix; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IxpathVisitor<TResult> typedVisitor = visitor as IxpathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespacePrefix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespacePrefixContext namespacePrefix() {
		NamespacePrefixContext _localctx = new NamespacePrefixContext(Context, State);
		EnterRule(_localctx, 8, RULE_namespacePrefix);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42; _localctx.name = Match(IDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributeContext : ParserRuleContext {
		public NamespacePrefixContext ns;
		public IToken name;
		public ITerminalNode AT() { return GetToken(xpathParser.AT, 0); }
		public ITerminalNode IDENT() { return GetToken(xpathParser.IDENT, 0); }
		public ITerminalNode COLON() { return GetToken(xpathParser.COLON, 0); }
		public NamespacePrefixContext namespacePrefix() {
			return GetRuleContext<NamespacePrefixContext>(0);
		}
		public AttributeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribute; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IxpathVisitor<TResult> typedVisitor = visitor as IxpathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttribute(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttributeContext attribute() {
		AttributeContext _localctx = new AttributeContext(Context, State);
		EnterRule(_localctx, 10, RULE_attribute);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44; Match(AT);
			State = 48;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				{
				State = 45; _localctx.ns = namespacePrefix();
				State = 46; Match(COLON);
				}
				break;
			}
			State = 50; _localctx.name = Match(IDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementContext : ParserRuleContext {
		public NamespacePrefixContext ns;
		public IToken name;
		public ITerminalNode IDENT() { return GetToken(xpathParser.IDENT, 0); }
		public ITerminalNode COLON() { return GetToken(xpathParser.COLON, 0); }
		public NamespacePrefixContext namespacePrefix() {
			return GetRuleContext<NamespacePrefixContext>(0);
		}
		public ElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_element; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IxpathVisitor<TResult> typedVisitor = visitor as IxpathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementContext element() {
		ElementContext _localctx = new ElementContext(Context, State);
		EnterRule(_localctx, 12, RULE_element);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				State = 52; _localctx.ns = namespacePrefix();
				State = 53; Match(COLON);
				}
				break;
			}
			State = 57; _localctx.name = Match(IDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3\r>");
		sb.Append("\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a");
		sb.Append("\t\a\x4\b\t\b\x3\x2\x3\x2\x6\x2\x13\n\x2\r\x2\xE\x2\x14\x3\x3");
		sb.Append("\x5\x3\x18\n\x3\x3\x3\x3\x3\x5\x3\x1C\n\x3\x3\x3\x5\x3\x1F\n");
		sb.Append("\x3\x3\x4\x3\x4\x3\x4\x5\x4$\n\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3");
		sb.Append("\x5\x3\x5\x3\x5\x3\x6\x3\x6\x3\a\x3\a\x3\a\x3\a\x5\a\x33\n\a");
		sb.Append("\x3\a\x3\a\x3\b\x3\b\x3\b\x5\b:\n\b\x3\b\x3\b\x3\b\x2\x2\t\x2");
		sb.Append("\x4\x6\b\n\f\xE\x2\x2=\x2\x12\x3\x2\x2\x2\x4\x1E\x3\x2\x2\x2");
		sb.Append("\x6 \x3\x2\x2\x2\b)\x3\x2\x2\x2\n,\x3\x2\x2\x2\f.\x3\x2\x2\x2");
		sb.Append("\xE\x39\x3\x2\x2\x2\x10\x11\a\x5\x2\x2\x11\x13\x5\x4\x3\x2\x12");
		sb.Append("\x10\x3\x2\x2\x2\x13\x14\x3\x2\x2\x2\x14\x12\x3\x2\x2\x2\x14");
		sb.Append("\x15\x3\x2\x2\x2\x15\x3\x3\x2\x2\x2\x16\x18\x5\b\x5\x2\x17\x16");
		sb.Append("\x3\x2\x2\x2\x17\x18\x3\x2\x2\x2\x18\x19\x3\x2\x2\x2\x19\x1B");
		sb.Append("\x5\xE\b\x2\x1A\x1C\x5\x6\x4\x2\x1B\x1A\x3\x2\x2\x2\x1B\x1C");
		sb.Append("\x3\x2\x2\x2\x1C\x1F\x3\x2\x2\x2\x1D\x1F\x5\f\a\x2\x1E\x17\x3");
		sb.Append("\x2\x2\x2\x1E\x1D\x3\x2\x2\x2\x1F\x5\x3\x2\x2\x2 #\a\x6\x2\x2");
		sb.Append("!$\x5\f\a\x2\"$\x5\xE\b\x2#!\x3\x2\x2\x2#\"\x3\x2\x2\x2$%\x3");
		sb.Append("\x2\x2\x2%&\a\t\x2\x2&\'\a\f\x2\x2\'(\a\a\x2\x2(\a\x3\x2\x2");
		sb.Append("\x2)*\a\x3\x2\x2*+\a\v\x2\x2+\t\x3\x2\x2\x2,-\a\x4\x2\x2-\v");
		sb.Append("\x3\x2\x2\x2.\x32\a\b\x2\x2/\x30\x5\n\x6\x2\x30\x31\a\n\x2\x2");
		sb.Append("\x31\x33\x3\x2\x2\x2\x32/\x3\x2\x2\x2\x32\x33\x3\x2\x2\x2\x33");
		sb.Append("\x34\x3\x2\x2\x2\x34\x35\a\x4\x2\x2\x35\r\x3\x2\x2\x2\x36\x37");
		sb.Append("\x5\n\x6\x2\x37\x38\a\n\x2\x2\x38:\x3\x2\x2\x2\x39\x36\x3\x2");
		sb.Append("\x2\x2\x39:\x3\x2\x2\x2:;\x3\x2\x2\x2;<\a\x4\x2\x2<\xF\x3\x2");
		sb.Append("\x2\x2\t\x14\x17\x1B\x1E#\x32\x39");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());


}
} // namespace GillSoft.ExpressionEvaluator
