//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyConfiguration("AssemblyConfiguration goes here")]
[assembly: AssemblyCompany("GillSoft Limited")]
[assembly: AssemblyCopyright("Copyright GillSoft 2013.")]
[assembly: AssemblyDescription("Read EULA for details. This is important information, please read it to the end.\r" +
    "\nThough every care has been taken to make this software as bug-free as possible," +
    " this software is provided on as-is basis. GillSoft will not be held responsible" +
    " for any kind of loss %28data, life, financial or any other type%29 caused by th" +
    "e usage of this software. Bugs may be fixed and fixed software may be released t" +
    "otally at the discretion of GillSoft.\r\nThis software has been developed by follo" +
    "wing the requirements provided by the client in good faith. GillSoft cannot be h" +
    "eld responsible for any illegal activity that might have been carried out by the" +
    " client using this software.\r\nThis software is the property of GillSoft and the " +
    "client is a registered user. Reverse engineering, debugging or any activity othe" +
    "r than the intended purpose carried out on this software will be dealt with maxi" +
    "mum force of the law.\r\nIt is illegal to Sell / Rent / Let-out / Share this softw" +
    "are without prior permission from GillSoft.\r\nAny activity which is not in the be" +
    "st interests of GillSoft will render the permission to use this software cancell" +
    "ed.\r\nAll intellectual rights of this software lie with GillSoft.\r\nIgnorance will" +
    " not be taken as excuse. You, as a user, have been warned.\r\nYou may proceed to u" +
    "se this software at your own risk. If you do not accept these terms, please clos" +
    "e the application.\r\nClicking on the %27Accept%27 button will imply that you agre" +
    "e to this EULA.\r\nTerms used in this document:\r\n1. EULA stands for End User Licen" +
    "sing Agreement.\r\n2. GillSoft refers to GillSoft Pvt. Ltd %28India%29 and GillSof" +
    "t Limtied %28Ireland%29.\r\n3. Registered User, Client refer to same person%28s%29" +
    "/Organisation%28s%29 to whom the license has been given GillSoft to use this sof" +
    "tware.\r\n4. User refers to the person who is actually carrying out any kind of ac" +
    "tivity using this software.")]
[assembly: AssemblyFileVersion("2017.3.28.2142")]
[assembly: AssemblyProduct("GillSoft.ExpressionEvaluator - By GillSoft Limited")]
[assembly: AssemblyTitle("GillSoft.ExpressionEvaluator")]
[assembly: AssemblyTrademark("Read EULA for details.")]
[assembly: AssemblyVersion("2017.3.28.2142")]
[assembly: AssemblyInformationalVersion("6febd64 - 2017.3.28.2142")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyConfiguration = "AssemblyConfiguration goes here";
    
    internal const string AssemblyCompany = "GillSoft Limited";
    
    internal const string AssemblyCopyright = "Copyright GillSoft 2013.";
    
    internal const string AssemblyDescription = "Read EULA for details. This is important information, please read it to the end.\r" +
        "\nThough every care has been taken to make this software as bug-free as possible," +
        " this software is provided on as-is basis. GillSoft will not be held responsible" +
        " for any kind of loss %28data, life, financial or any other type%29 caused by th" +
        "e usage of this software. Bugs may be fixed and fixed software may be released t" +
        "otally at the discretion of GillSoft.\r\nThis software has been developed by follo" +
        "wing the requirements provided by the client in good faith. GillSoft cannot be h" +
        "eld responsible for any illegal activity that might have been carried out by the" +
        " client using this software.\r\nThis software is the property of GillSoft and the " +
        "client is a registered user. Reverse engineering, debugging or any activity othe" +
        "r than the intended purpose carried out on this software will be dealt with maxi" +
        "mum force of the law.\r\nIt is illegal to Sell / Rent / Let-out / Share this softw" +
        "are without prior permission from GillSoft.\r\nAny activity which is not in the be" +
        "st interests of GillSoft will render the permission to use this software cancell" +
        "ed.\r\nAll intellectual rights of this software lie with GillSoft.\r\nIgnorance will" +
        " not be taken as excuse. You, as a user, have been warned.\r\nYou may proceed to u" +
        "se this software at your own risk. If you do not accept these terms, please clos" +
        "e the application.\r\nClicking on the %27Accept%27 button will imply that you agre" +
        "e to this EULA.\r\nTerms used in this document:\r\n1. EULA stands for End User Licen" +
        "sing Agreement.\r\n2. GillSoft refers to GillSoft Pvt. Ltd %28India%29 and GillSof" +
        "t Limtied %28Ireland%29.\r\n3. Registered User, Client refer to same person%28s%29" +
        "/Organisation%28s%29 to whom the license has been given GillSoft to use this sof" +
        "tware.\r\n4. User refers to the person who is actually carrying out any kind of ac" +
        "tivity using this software.";
    
    internal const string AssemblyFileVersion = "2017.3.28.2142";
    
    internal const string AssemblyProduct = "GillSoft.ExpressionEvaluator - By GillSoft Limited";
    
    internal const string AssemblyTitle = "GillSoft.ExpressionEvaluator";
    
    internal const string AssemblyTrademark = "Read EULA for details.";
    
    internal const string AssemblyVersion = "2017.3.28.2142";
    
    internal const string AssemblyInformationalVersion = "6febd64 - 2017.3.28.2142";
    
    private ThisAssembly() {
    }
}
